apiVersion: v1
kind: StatefulSet
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: app
        image: cr.yandex/crp5i2al1h7vacmtgpnm/todo2:amd64
        ports:
          - containerPort: 80
            name: "http-server"
        resources:
          requests:
            memory: 250Mi
            cpu: 300m
          limits:
            memory: 1Gi
            cpu: 600m
        env:
          - name: DATABASE_HOSTS
            value: postgres-service
          - name: DATABASE_URI
            value: postgresql://username:password@postgres-service:5432/hw_db?sslmode=disable
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - vault
              topologyKey: kubernetes.io/hostname