apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    app: app
spec:
  containers:
    - image: postgres
      name: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: username
        - name: POSTGRES_DB
          value: hw_db
        - name: PGDATA
          value: /var/lib/postgresql/data/hw_db
      ports:
        - containerPort: 5432
          name: postgres
      volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data/
      resources:
        requests:
          memory: 250Mi
          cpu: 300m
        limits:
          memory: 1Gi
          cpu: 600m
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: postgres-claim
